### ISSUE TITLE
Can't install with sulu 2.4

### ISSUE THREAD

**Issue by axoloth** [sulu/SuluCommunityBundle#147]
| Q | A
| --- | ---
| Bug? | yes
| New Feature? | no
| Community Bundle Version | 2.0@dev
| Sulu Version | 2.4
| Browser Version | All

#### Actual Behavior

The bundle won't install.

 [InvalidArgumentException]                                                                                    
 Could not find package sulu/community-bundle in a version matching "2.0@dev" and a stability matching "dev". 

#### Expected Behavior

Make the bundle installation ok

#### Steps to Reproduce

composer require sulu/community-bundle:^2.0@dev --no-scripts

#### Possible Solutions

Update composer.json

**Comment by GandonNicolas** [comment]
I have the same problem right now. Have you found a solution?

**Comment by alexander-schranz** [comment]
Hello the community bundle is not yet tagged for Sulu `2.0` as there is still a bc break on the roadmap for it: https://github.com/sulu/SuluCommunityBundle/issues/146.

Currently you are saved to use `^2.0@dev` until but keep in mind if you use that 2 entities in your code that that bc break will come and that this model / tables will be renamed.

**Comment by alexander-schranz** [comment]
The installation with JMS serializer 4.0 is fixed in: https://github.com/sulu/SuluCommunityBundle/pull/151 so if you had that installed it should know also work.

Sometimes the easiest way to findout something blocking is going with:

```bash
composer require sulu/community-bundle:^2.0@dev --no-update
composer update
```

This way composer allows also downgrades of maybe a library which a newer version currently is installed.
